from vehicle_api.app.models import Vehicle
from vehicle_api.extensions import (
    cors,
    db,
    csrf_protect,
    migrate,
)

data = { 
    "all_vehicles": 
[
    {
        "last_mileage_reported": 4020,
        "license_plate_number": "1DMP23",
        "license_plate_state": "MA",
        "make": "Ford",
        "miles_until_service": 3480,
        "model": "Titanium",
        "status": "available",
        "id": "db99d2a1-6e5b-49dc-91f4-738caf09dcde",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 8860,
        "license_plate_number": "8PCV522",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 5140,
        "model": "Sportage",
        "status": "on_rent",
        "id": "a22a0a86-5242-4ec6-87a5-8991a70efb04",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 12313,
        "license_plate_number": "8PJU280",
        "license_plate_state": "CA",
        "make": "Kia ",
        "miles_until_service": 3901,
        "model": "Optima",
        "status": "maintenance",
        "id": "4a85e857-a9bf-4785-84a3-2afba05477f8",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 14650,
        "license_plate_number": "8PTY478",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 3072,
        "model": "Tucson",
        "status": "on_rent",
        "id": "cd24476f-90c8-46a0-b1f3-9f5f4c6b2bb7",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 26472,
        "license_plate_number": "HEV7531",
        "license_plate_state": "NC",
        "make": "Jeep",
        "miles_until_service": 3028,
        "model": "Compass",
        "status": "available",
        "id": "a95d9653-0a0b-4f8a-83d2-8b9fd2a36bdb",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9137,
        "license_plate_number": "8NOZ643",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 363,
        "model": "Tuscon",
        "status": "maintenance",
        "id": "434bf2e1-1326-437e-baf5-52df20f2b0d5",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 10992,
        "license_plate_number": "506L82",
        "license_plate_state": "NV",
        "make": "Toyota",
        "miles_until_service": 8008,
        "model": "Rav 4",
        "status": "available",
        "id": "b39923a0-f0a3-4a6b-a7d7-fcc774c453d8",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 6069,
        "license_plate_number": "8PWL249",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1431,
        "model": "Camry",
        "status": "on_rent",
        "id": "529f1856-9568-4913-9c55-e79532bc1d8f",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 23395,
        "license_plate_number": "8LTU346",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 6505,
        "model": "Versa",
        "status": "available",
        "id": "ca563ec3-e5ff-4da2-b191-4d4b0ae447b6",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 23588,
        "license_plate_number": "8PLZ648",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 7912,
        "model": "EcoSport",
        "status": "maintenance",
        "id": "781df3f4-08b0-402b-a95c-f0a13a73c905",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 3658,
        "license_plate_number": "786M14",
        "license_plate_state": "NV",
        "make": "Mitsubishi",
        "miles_until_service": 1843,
        "model": "Outlander Sport",
        "status": "on_rent",
        "id": "92227ed6-622c-4df3-9707-cdd94c1671df",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 11579,
        "license_plate_number": "8PLZ035",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 408,
        "model": "Optima",
        "status": "available",
        "id": "1682b451-b069-4a54-b164-a58f105a54f8",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 8767,
        "license_plate_number": "8RBH973",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": -1267,
        "model": "Altima",
        "status": "available",
        "id": "316f1a87-6036-451c-8b59-435b33c79547",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 18919,
        "license_plate_number": "8PTZ738",
        "license_plate_state": "CA",
        "make": "Mitsubishi",
        "miles_until_service": 3235,
        "model": "Outlander Sport",
        "status": "on_rent",
        "id": "d1838c45-a1fc-43a2-acb9-be6e88ee955d",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 10963,
        "license_plate_number": "8NOZ013",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 4537,
        "model": "Elantra",
        "status": "on_rent",
        "id": "f90d844c-19ac-422f-88ef-4d3bf3847063",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 15461,
        "license_plate_number": "8LOZ294",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 7133,
        "model": "Camry",
        "status": "on_rent",
        "id": "3050e61c-5ecb-4f93-93db-4abddd2d76ea",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 23288,
        "license_plate_number": "KRG5765",
        "license_plate_state": "PA",
        "make": "Hyundai ",
        "miles_until_service": 4112,
        "model": "Elantra",
        "status": "available",
        "id": "b6795cf8-31c5-4e70-96d1-d5a8d37d3af3",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 10056,
        "license_plate_number": "ELN238",
        "license_plate_state": "MN",
        "make": "Mitsubishi ",
        "miles_until_service": 944,
        "model": "Outlander",
        "status": "on_rent",
        "id": "cf4a5394-9350-4214-9351-3b525bb9b367",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 3401,
        "license_plate_number": "8SAJ753",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 4099,
        "model": "Versa",
        "status": "available",
        "id": "54e8e99e-fc38-493b-913d-fa5503263435",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 30885,
        "license_plate_number": "8NXE944",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 4404,
        "model": "Versa",
        "status": "on_rent",
        "id": "bd85edba-5d62-4090-bf5f-14f5dcad5b75",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 18294,
        "license_plate_number": "8PTY242",
        "license_plate_state": "CA",
        "make": "Jeep",
        "miles_until_service": -1016,
        "model": "Compass",
        "status": "available",
        "id": "d31f04e5-eea2-4ea5-8853-fde9449e37d1",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 7407,
        "license_plate_number": "8PLY182",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 2093,
        "model": "Camry",
        "status": "on_rent",
        "id": "88771b96-d4fc-44fa-8284-04f4b978c569",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 1924,
        "license_plate_number": "8NYL629",
        "license_plate_state": "CA",
        "make": "Mazda",
        "miles_until_service": 7077,
        "model": "CX-5",
        "status": "on_rent",
        "id": "43d69856-eac1-46e5-b26e-48282e31e8e7",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 6738,
        "license_plate_number": "8LDY993",
        "license_plate_state": "CA",
        "make": "GMC",
        "miles_until_service": 762,
        "model": "Terrain",
        "status": "on_rent",
        "id": "82e2bb02-0ad3-45fb-b601-4a60f78cf4e1",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 10875,
        "license_plate_number": "8RBH387",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 8125,
        "model": "EcoSport",
        "status": "maintenance",
        "id": "cb30c413-199b-4132-ae45-973aa84502e2",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 12820,
        "license_plate_number": "8NYL026",
        "license_plate_state": "CA",
        "make": "Jeep",
        "miles_until_service": 2180,
        "model": "Compass",
        "status": "on_rent",
        "id": "2b89ffa8-2fda-4f70-be97-9c4a15922a8f",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 7581,
        "license_plate_number": "8RBJ632",
        "license_plate_state": "CA",
        "make": "Honda",
        "miles_until_service": -81,
        "model": "CRV",
        "status": "on_rent",
        "id": "bb95cb2b-6877-4237-a890-40594304682d",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 11755,
        "license_plate_number": "8PLY261",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 7245,
        "model": "Rav 4",
        "status": "on_rent",
        "id": "795fd86d-b90a-4568-b8ed-3908be5760d6",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 476,
        "license_plate_number": "8TEB510",
        "license_plate_state": "CA",
        "make": "VW",
        "miles_until_service": 7024,
        "model": "Passat",
        "status": "available",
        "id": "15d7d5a1-2c8f-4a5a-ae0e-2cd1c509978b",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 20521,
        "license_plate_number": "8NOZ042",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 4479,
        "model": "Elantra",
        "status": "on_rent",
        "id": "97d889b3-e4d6-4a45-a32c-0b50942d8641",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 30098,
        "license_plate_number": "752L20",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 3014,
        "model": "Compass",
        "status": "available",
        "id": "c56a8d94-28f7-4583-9fcf-cabe176b6039",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 8284,
        "license_plate_number": "BTB8546",
        "license_plate_state": "WA",
        "make": "Toyota",
        "miles_until_service": 1216,
        "model": "Camry",
        "status": "maintenance",
        "id": "dce4eb93-73dd-4326-a94b-7b93648c7cba",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 15366,
        "license_plate_number": "8NYK778",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 5134,
        "model": "Rav 4",
        "status": "on_rent",
        "id": "c9de10b0-c48a-409e-b03c-3f15ee5b990e",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 13579,
        "license_plate_number": "2KZL74",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 4850,
        "model": "Optima LX",
        "status": "available",
        "id": "a2daaca7-b411-40ae-8a8d-59e727dc3b26",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 16980,
        "license_plate_number": "8NYK641",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 6591,
        "model": "Camry",
        "status": "on_rent",
        "id": "08688a31-d2de-45ed-88a4-55f39b21ff6e",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 20579,
        "license_plate_number": "8PLZ663",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 3202,
        "model": "Ecosport",
        "status": "on_rent",
        "id": "c7a76d8b-fd5d-4f36-b1b2-3335e49aed07",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6169,
        "license_plate_number": "8PKE467",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": -668,
        "model": "Kona",
        "status": "available",
        "id": "c05034cc-53f6-4e17-b1cb-4ad0ec5cb72f",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 10659,
        "license_plate_number": "8PKD726",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 6841,
        "model": "Kona",
        "status": "maintenance",
        "id": "3050973e-7c51-40ce-b43e-f8bab8d055f6",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5395,
        "license_plate_number": "G185DM",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": 2105,
        "model": "Versa",
        "status": "maintenance",
        "id": "dec86f78-3d5a-4547-ae4e-be64eb3994d5",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7490,
        "license_plate_number": "8PKF921",
        "license_plate_state": "CA",
        "make": "KIA ",
        "miles_until_service": 4437,
        "model": "Soul",
        "status": "on_rent",
        "id": "9603ce3c-fd8a-4c7d-8b10-fe9788cc4fa7",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 18422,
        "license_plate_number": "KIB653",
        "license_plate_state": "OK",
        "make": "Hyundai",
        "miles_until_service": 3157,
        "model": "Elantra",
        "status": "on_rent",
        "id": "9126d021-ee26-4a72-a3e9-1f9a5f447919",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 7188,
        "license_plate_number": "JJHF63",
        "license_plate_state": "FL",
        "make": "Volvo",
        "miles_until_service": 2812,
        "model": "S60",
        "status": "available",
        "id": "d49eeb38-d584-4c33-923f-b45ea348cd69",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 11486,
        "license_plate_number": "8NYM878",
        "license_plate_state": "CA",
        "make": "Mitsubishi",
        "miles_until_service": 2434,
        "model": "Outlander",
        "status": "on_rent",
        "id": "bd0482c4-85b6-4da4-a30d-fc1147c8f88b",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 22349,
        "license_plate_number": "8PCV065",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 2386,
        "model": "Tucson",
        "status": "on_rent",
        "id": "0d4ff8db-7a07-4c47-9438-9fd705fb5247",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 5992,
        "license_plate_number": "9WT442",
        "license_plate_state": "MA",
        "make": "Mitzubishi",
        "miles_until_service": 1508,
        "model": "Outlander",
        "status": "on_rent",
        "id": "a5760417-faf6-4c5c-b8e9-da448caa2984",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 17818,
        "license_plate_number": "8NOY074",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 5882,
        "model": "Edge",
        "status": "available",
        "id": "e5a80996-be83-417c-806d-f2a7b7c1193b",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 26358,
        "license_plate_number": "8LOH261",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 4148,
        "model": "Sonata",
        "status": "available",
        "id": "519b72b6-442d-4c71-8214-2766536fcc86",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 13749,
        "license_plate_number": "9WM592",
        "license_plate_state": "MA",
        "make": "Mitzubishi",
        "miles_until_service": 4860,
        "model": "Outlander",
        "status": "available",
        "id": "1ce8d168-3720-42d4-a5bb-37ad418303a2",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 12774,
        "license_plate_number": "CTY1163",
        "license_plate_state": "AZ",
        "make": "Toyota",
        "miles_until_service": 6033,
        "model": "Camry",
        "status": "available",
        "id": "edabfd3c-cdbb-41af-ae78-aeea3c230961",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 12543,
        "license_plate_number": "BSF7408",
        "license_plate_state": "WA",
        "make": "Toyota",
        "miles_until_service": 4222,
        "model": "Camry",
        "status": "maintenance",
        "id": "3e94dfef-2fbf-451d-9c7e-aa8df3b39348",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 3187,
        "license_plate_number": "8JQA827",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 13181,
        "model": "Eco Sport",
        "status": "available",
        "id": "2f6ef833-8752-42e8-8359-67b34df71b68",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5393,
        "license_plate_number": "8RBK690",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2107,
        "model": "Altima",
        "status": "available",
        "id": "d3048599-86c8-467a-89e3-f1215390b0c2",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 12786,
        "license_plate_number": "8NOZ711",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 2214,
        "model": "Forte",
        "status": "on_rent",
        "id": "88ba16b7-df54-4529-86ee-a029cd6ede15",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 4210,
        "license_plate_number": "8PKF842",
        "license_plate_state": "CA",
        "make": "Mitsubishi ",
        "miles_until_service": 1291,
        "model": "Outlander Sport",
        "status": "on_rent",
        "id": "95430470-c3c1-4d85-a0e0-3d53c8da1abc",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 15750,
        "license_plate_number": "8NOZ665",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 3802,
        "model": "Forte",
        "status": "on_rent",
        "id": "f5b72539-2c32-400d-a497-aa03e330bd8b",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 14163,
        "license_plate_number": "8KHF624",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 4078,
        "model": "Forte",
        "status": "available",
        "id": "7286d32c-cda3-42e5-a2cd-c6a17c644441",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 32855,
        "license_plate_number": "159L06",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 6167,
        "model": "Compass",
        "status": "on_rent",
        "id": "9e61beee-22ee-41b9-ae58-623018d765cd",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 3329,
        "license_plate_number": "8SAJ734",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 4171,
        "model": "Versa",
        "status": "on_rent",
        "id": "fccef2d7-310f-4c8e-939e-dff41cbec910",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6185,
        "license_plate_number": "8RAL244",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 3315,
        "model": "Escape",
        "status": "on_rent",
        "id": "05bf735d-823b-4aeb-9b9a-90a006a0eaf6",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 10405,
        "license_plate_number": "8PKF213",
        "license_plate_state": "CA",
        "make": "Mazda",
        "miles_until_service": 4003,
        "model": "CX-5",
        "status": "on_rent",
        "id": "cc040e7d-9065-44ab-8525-30176409b3ce",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 8050,
        "license_plate_number": "8PWL541",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": -550,
        "model": "Escape",
        "status": "available",
        "id": "2d5e268b-d838-418a-9e25-b7d96f6dbba6",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 11117,
        "license_plate_number": "8PJU279",
        "license_plate_state": "CA",
        "make": "Kia ",
        "miles_until_service": 5198,
        "model": "Optima",
        "status": "available",
        "id": "9496e256-4cc4-436d-ba7a-1a8bfda18fdc",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6436,
        "license_plate_number": "8PWK926",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 1064,
        "model": "Altima",
        "status": "available",
        "id": "ec458af5-a73b-441b-a386-45f6985271a9",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 25353,
        "license_plate_number": "8PLY267",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1404,
        "model": "Corolla",
        "status": "maintenance",
        "id": "b0c8b89b-4c83-4085-b2a3-6a3c586f5604",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6899,
        "license_plate_number": "8RBJ537",
        "license_plate_state": "CA",
        "make": "Honda",
        "miles_until_service": 7356,
        "model": "Accord",
        "status": "available",
        "id": "190f27d1-9cd8-4a5c-927c-34a21679a9f9",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 8829,
        "license_plate_number": "8PKF738",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 4171,
        "model": "Altima",
        "status": "available",
        "id": "e74593d4-8964-42c8-8e37-226f45ac50fb",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 8010,
        "license_plate_number": "8PWL522",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 1491,
        "model": "Escape",
        "status": "on_rent",
        "id": "1eeddcbc-d69a-4aab-ae5a-1a556704ecf3",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 42077,
        "license_plate_number": "8GXG883",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 5457,
        "model": "Versa",
        "status": "on_rent",
        "id": "1d97dedb-b575-4142-92f8-d30561e46321",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 11319,
        "license_plate_number": "8PLY894",
        "license_plate_state": "CA",
        "make": "Jeep",
        "miles_until_service": 6249,
        "model": "Compass Trailhawk",
        "status": "on_rent",
        "id": "192d6798-9c2a-4f03-ac12-02bc79eb67fd",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 12570,
        "license_plate_number": "BTP1368",
        "license_plate_state": "WA",
        "make": "Ford",
        "miles_until_service": 6430,
        "model": "Escape",
        "status": "maintenance",
        "id": "3ae5978c-ffa3-493f-8095-3cd5839a6970",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 8180,
        "license_plate_number": "8RVY003",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 3877,
        "model": "Altima",
        "status": "on_rent",
        "id": "5641eb4d-fb5d-4d08-afa9-df3b19c7f648",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 25912,
        "license_plate_number": "8KMZ890",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 4198,
        "model": "Camry",
        "status": "on_rent",
        "id": "2cdc88ad-ff39-464d-938a-88ec8281668c",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6467,
        "license_plate_number": "773M14",
        "license_plate_state": "NV",
        "make": "Mitsubishi",
        "miles_until_service": 5873,
        "model": "Outlander",
        "status": "on_rent",
        "id": "70d7989a-f112-4ecd-844e-c868ae5b665a",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 8485,
        "license_plate_number": "BRU8237",
        "license_plate_state": "CA",
        "make": "Jeep",
        "miles_until_service": 1015,
        "model": "Compass",
        "status": "available",
        "id": "3d021fac-9e55-4806-b505-1b9bb36aded1",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 12485,
        "license_plate_number": "BTP3327",
        "license_plate_state": "WA",
        "make": "Mitsubishi",
        "miles_until_service": 388,
        "model": "Outlander",
        "status": "available",
        "id": "7dd8fff2-d166-4f79-8b5c-e48f2e9e0c82",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 11909,
        "license_plate_number": "8NYM128",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 5277,
        "model": "Camry",
        "status": "on_rent",
        "id": "723bf118-b887-4b79-a618-62c99bca8450",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5364,
        "license_plate_number": "8PWM520",
        "license_plate_state": "CA",
        "make": "Mazda",
        "miles_until_service": 1636,
        "model": "CX-5",
        "status": "available",
        "id": "610a676a-8117-47c4-adb7-2de0895b5ac7",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9986,
        "license_plate_number": "BTP1837",
        "license_plate_state": "WA",
        "make": "Mitsubishi",
        "miles_until_service": 2770,
        "model": "Outlander",
        "status": "maintenance",
        "id": "546a236d-df31-4463-8773-e2f329516c11",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 12814,
        "license_plate_number": "JKWT48",
        "license_plate_state": "FL",
        "make": "GMC",
        "miles_until_service": 2186,
        "model": "Terrain",
        "status": "maintenance",
        "id": "ff5df488-b326-4ad9-a35a-c4e8c1f2aa6b",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9742,
        "license_plate_number": "8RBJ399",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 5758,
        "model": "Kona",
        "status": "on_rent",
        "id": "e9455044-1a2e-4d76-b4aa-2333e3645ebf",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 0,
        "license_plate_number": "DUMMYDG1",
        "license_plate_state": "MA",
        "make": "Chrysler",
        "miles_until_service": 7500,
        "model": "Accord",
        "status": "available",
        "id": "dc0a9799-ba24-4979-8a99-118e914a5f05",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 38987,
        "license_plate_number": "386H73",
        "license_plate_state": "NV",
        "make": "Hyundai",
        "miles_until_service": 4360,
        "model": "Elantra",
        "status": "on_rent",
        "id": "816be287-304f-4727-a47b-64626940c096",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 12512,
        "license_plate_number": "8PLZ697",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 4517,
        "model": "Camry",
        "status": "on_rent",
        "id": "68a01b25-9f03-42a0-bc56-dcacd108e323",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 14530,
        "license_plate_number": "CTL4396",
        "license_plate_state": "AZ",
        "make": "Kia",
        "miles_until_service": 4156,
        "model": "Optima",
        "status": "available",
        "id": "6b8a17fa-76a0-4183-a56c-edbbacf71161",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 10173,
        "license_plate_number": "1ART43",
        "license_plate_state": "MA",
        "make": "Mazda",
        "miles_until_service": 4158,
        "model": "CX-5",
        "status": "available",
        "id": "10497497-7b1e-4959-8869-a81bc51f0272",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 6598,
        "license_plate_number": "8PWK627",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 902,
        "model": "Camry",
        "status": "available",
        "id": "d625b573-b8b6-4ec3-bb5e-62b0f239a9a7",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 25373,
        "license_plate_number": "006L91",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 6691,
        "model": "Compass",
        "status": "available",
        "id": "84878adf-b265-4e6c-9a30-61d0ebed25ee",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 14551,
        "license_plate_number": "8JQA865",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 2449,
        "model": "ECO Sport",
        "status": "available",
        "id": "257849e8-e9f5-472e-9b3e-98e528da3b7b",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 22373,
        "license_plate_number": "757L20",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 7167,
        "model": "Compass",
        "status": "available",
        "id": "24efbfdd-2326-46f1-883c-fb563bc570f4",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 17817,
        "license_plate_number": "CTLD15",
        "license_plate_state": "FL",
        "make": "Toyota",
        "miles_until_service": 4683,
        "model": "Corolla",
        "status": "on_rent",
        "id": "1a8725a7-ebe4-4a83-beec-ce9d9bd40c33",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5451,
        "license_plate_number": "8RAM368",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 50,
        "model": "Sentra",
        "status": "on_rent",
        "id": "ae265eec-29c4-4471-a0af-940232aa7af3",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 7199,
        "license_plate_number": "8PWL289",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 301,
        "model": "Altima",
        "status": "available",
        "id": "61249cea-56e7-455a-8fd3-41c8e8fc21bd",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 4965,
        "license_plate_number": "8RBJ680",
        "license_plate_state": "CA",
        "make": "Mitsubishi",
        "miles_until_service": 2535,
        "model": "Outlander",
        "status": "maintenance",
        "id": "6a5922d9-fd3c-4d0f-959f-2ed436018b05",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 5657,
        "license_plate_number": "8RBJ748",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 1843,
        "model": "Altima",
        "status": "on_rent",
        "id": "e5a6419d-f828-47fe-8598-2cb782f04953",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 14407,
        "license_plate_number": "2KZL84",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 5547,
        "model": "Optima LX",
        "status": "on_rent",
        "id": "cdbf4043-6af2-4377-bd47-787ad3f4c358",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 3187,
        "license_plate_number": "8RAM436",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 2314,
        "model": "Rio ",
        "status": "on_rent",
        "id": "9d31e3ff-1d03-4842-9b8d-fa6482204e8a",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 12037,
        "license_plate_number": "8PKF363",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 4963,
        "model": "Corolla",
        "status": "on_rent",
        "id": "bdc745ea-14fe-4ff0-937f-d9ba14c28967",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 33207,
        "license_plate_number": "FL430ABZ",
        "license_plate_state": "IN",
        "make": "Toyota",
        "miles_until_service": 4793,
        "model": "Corolla",
        "status": "maintenance",
        "id": "b9bd38ca-a1a1-4aca-944d-824c25f143b9",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 14099,
        "license_plate_number": "AEWC44",
        "license_plate_state": "FL",
        "make": "VW",
        "miles_until_service": 5103,
        "model": "Jetta",
        "status": "available",
        "id": "647d2d60-b087-406e-b224-08a6fe440ee5",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 8439,
        "license_plate_number": "8PTZ134",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1061,
        "model": "Corolla",
        "status": "on_rent",
        "id": "22b54e7b-5f21-4509-b08f-da237707bc76",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 12987,
        "license_plate_number": "8LOZ458",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 3898,
        "model": "Camry",
        "status": "available",
        "id": "401c8547-3c2a-463e-ac45-3b467e2ed201",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 12130,
        "license_plate_number": "ELN126",
        "license_plate_state": "MN",
        "make": "Toyota",
        "miles_until_service": 5317,
        "model": "Camry",
        "status": "maintenance",
        "id": "98fc93d7-3969-4533-b2e0-f87ce041c1a6",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 0,
        "license_plate_number": "DUMMYDG2",
        "license_plate_state": "MA",
        "make": "Chevy",
        "miles_until_service": 7500,
        "model": "Accent",
        "status": "maintenance",
        "id": "32797a94-4dbd-43df-9de5-c28d137afd10",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 8074,
        "license_plate_number": "8PKE867",
        "license_plate_state": "CA",
        "make": "Hyundai ",
        "miles_until_service": 6926,
        "model": "Tucson",
        "status": "on_rent",
        "id": "53d6774a-1b3e-4ad3-8e06-0732ba100b3f",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 16219,
        "license_plate_number": "782M14",
        "license_plate_state": "NV",
        "make": "Mitsubishi",
        "miles_until_service": 1907,
        "model": "Outlander Sport",
        "status": "available",
        "id": "2241c953-2aae-498c-8d4c-eb4ce7786ce2",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 12934,
        "license_plate_number": "8PWK816",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 7293,
        "model": "Camry",
        "status": "maintenance",
        "id": "9db9c5f4-cb03-4d73-8869-9e976b9f4c21",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 11989,
        "license_plate_number": "BTP3227",
        "license_plate_state": "WA",
        "make": "Nissan",
        "miles_until_service": 7011,
        "model": "Altima",
        "status": "available",
        "id": "776a3b57-0b27-46af-995b-8e0258c82f28",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 14886,
        "license_plate_number": "X70LXH",
        "license_plate_state": "NJ",
        "make": "Mitsubishi",
        "miles_until_service": 3614,
        "model": "Outlander",
        "status": "available",
        "id": "d645ce20-80e7-465c-8808-753484614ba4",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9639,
        "license_plate_number": "2KZL24",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 5162,
        "model": "Optima LX",
        "status": "on_rent",
        "id": "407a1061-385d-48dd-984a-7dbe40853f21",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 9950,
        "license_plate_number": "2KZL34",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 5416,
        "model": "Optima LX",
        "status": "available",
        "id": "0c8e0f99-9316-4935-bdf1-dfb261e5dba8",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 17285,
        "license_plate_number": "LKVD24",
        "license_plate_state": "FL",
        "make": "Mitsubishi",
        "miles_until_service": 2787,
        "model": "Outlander",
        "status": "available",
        "id": "525e09ff-6a5a-49e0-81c8-8628f6d7d083",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 25180,
        "license_plate_number": "759L20",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 5121,
        "model": "Compass",
        "status": "available",
        "id": "b3953c98-2a9c-415d-8419-c5e2ff813409",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 14604,
        "license_plate_number": "8PWM204",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 6896,
        "model": "Kona",
        "status": "available",
        "id": "b9ca9911-bbf5-43c1-b17b-c266b7fff677",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 20529,
        "license_plate_number": "8JQB359",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 2471,
        "model": "Elantra",
        "status": "maintenance",
        "id": "caa00aea-1824-47fb-ab24-6a79a14e2cd7",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 8849,
        "license_plate_number": "8RAM505",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 3342,
        "model": "Altima",
        "status": "available",
        "id": "ddbd5e1c-987f-4158-96f7-28f02905b948",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 18573,
        "license_plate_number": "598M14",
        "license_plate_state": "NV",
        "make": "Mazda",
        "miles_until_service": 423,
        "model": "CX-5",
        "status": "on_rent",
        "id": "c56325de-bfa6-48bb-a9f9-fc2fc7a6e0e5",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 11055,
        "license_plate_number": "8PKD713",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 1478,
        "model": "Tucson",
        "status": "on_rent",
        "id": "01443a1a-691f-4e73-97f3-740c95e1f30a",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 5008,
        "license_plate_number": "8RBK167",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2492,
        "model": "Altima",
        "status": "available",
        "id": "924f2df7-32ea-4626-a30f-7904423faba2",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 5926,
        "license_plate_number": "8PWM139",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1574,
        "model": "Camry",
        "status": "available",
        "id": "a6de9080-b072-48ac-8e2d-d5036dfa134a",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 11000,
        "license_plate_number": "8PKE896",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 1058,
        "model": "Kona",
        "status": "on_rent",
        "id": "63fe0d7a-3ac2-48f1-b5aa-d1757814403b",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6763,
        "license_plate_number": "8PLY775",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 737,
        "model": "Optima",
        "status": "available",
        "id": "0982200e-76bf-4911-acb4-63cb840b1bff",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5072,
        "license_plate_number": "8PWM610",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2428,
        "model": "Altima",
        "status": "on_rent",
        "id": "759ae48e-9dee-4801-8b3e-d59eb7c7d23a",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 22732,
        "license_plate_number": "BYX1320",
        "license_plate_state": "AZ",
        "make": "Kia",
        "miles_until_service": 5968,
        "model": "Forte",
        "status": "on_rent",
        "id": "63075ec5-42aa-44e9-87ff-af3302119bc8",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 10626,
        "license_plate_number": "8PJU276",
        "license_plate_state": "CA",
        "make": "Kia ",
        "miles_until_service": 3940,
        "model": "Optima",
        "status": "on_rent",
        "id": "adf1020d-84b6-46c6-b48d-d8ac9191867b",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 12957,
        "license_plate_number": "AX48629",
        "license_plate_state": "CT",
        "make": "Hyundai",
        "miles_until_service": 2043,
        "model": "Elantra",
        "status": "available",
        "id": "9233d6fa-cf06-46ae-bf53-5b2a86d43996",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5129,
        "license_plate_number": "8RAM445",
        "license_plate_state": "CA",
        "make": "Kia",
        "miles_until_service": 2372,
        "model": "Rio",
        "status": "available",
        "id": "98974a99-1b9d-4255-958a-32414a26c253",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 16876,
        "license_plate_number": "BTP3420",
        "license_plate_state": "WA",
        "make": "Mitsubishi",
        "miles_until_service": 6624,
        "model": "Outlander",
        "status": "maintenance",
        "id": "4e8b2166-c5d6-4e3f-89c8-124fbe571feb",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9098,
        "license_plate_number": "917L96",
        "license_plate_state": "NV",
        "make": "Hyundai",
        "miles_until_service": 3392,
        "model": "Kona",
        "status": "on_rent",
        "id": "36e73692-7e35-4d25-a1ff-3745df7c7515",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 3540,
        "license_plate_number": "402YUK",
        "license_plate_state": "FL",
        "make": "Volvo",
        "miles_until_service": 6460,
        "model": "V60",
        "status": "available",
        "id": "1f473a49-9226-4699-aa8a-b974741f67f4",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 13542,
        "license_plate_number": "8LDY047",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 4072,
        "model": "Corolla",
        "status": "available",
        "id": "b201fbb5-8cc4-44be-b962-569bda774b77",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 28549,
        "license_plate_number": "8LZE262",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 1845,
        "model": "Versa",
        "status": "on_rent",
        "id": "07468bfb-3838-43ba-83bb-b6f7144e7a25",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 4122,
        "license_plate_number": "1ATL23",
        "license_plate_state": "MA",
        "make": "Ford",
        "miles_until_service": 3378,
        "model": "Titanium",
        "status": "available",
        "id": "547908bf-c975-4c06-a921-f212158afd02",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 13639,
        "license_plate_number": "8NSE588",
        "license_plate_state": "CA",
        "make": "VW",
        "miles_until_service": 7017,
        "model": "Jetta",
        "status": "available",
        "id": "24c32505-12fa-4071-97f5-573d70f97ab9",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6488,
        "license_plate_number": "IENH82",
        "license_plate_state": "FL",
        "make": "Volvo",
        "miles_until_service": 3512,
        "model": "S60",
        "status": "on_rent",
        "id": "282224de-e5bd-4a47-b641-b158b43da893",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 30894,
        "license_plate_number": "8LOH281",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 7126,
        "model": "Sonata",
        "status": "available",
        "id": "b62d44c5-78f2-4d80-978d-32dc9ae3bb79",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 16948,
        "license_plate_number": "8NYM930",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 527,
        "model": "Camry",
        "status": "on_rent",
        "id": "703aac1b-d18b-40a8-8ad5-e3707ba512a7",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 13525,
        "license_plate_number": "8PWL516",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 3899,
        "model": "Escape",
        "status": "maintenance",
        "id": "80f68241-402e-4641-b6aa-9322d3d8e2e3",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 4609,
        "license_plate_number": "8RBK294",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2891,
        "model": "Altima",
        "status": "on_rent",
        "id": "74c67b9c-4267-4e98-970e-1b25b9b011d8",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 9481,
        "license_plate_number": "987JKK",
        "license_plate_state": "OR",
        "make": "Ford",
        "miles_until_service": 5620,
        "model": "Escape",
        "status": "on_rent",
        "id": "6ed3f93f-1589-42cf-b417-1e9d0c997f92",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 18951,
        "license_plate_number": "CPX9567",
        "license_plate_state": "AZ",
        "make": "Toyota",
        "miles_until_service": 6012,
        "model": "Corolla",
        "status": "available",
        "id": "4cb395ab-2620-4f16-9b8e-ab319cadf954",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7301,
        "license_plate_number": "8N0Z888",
        "license_plate_state": "CA",
        "make": "Mitsubishi",
        "miles_until_service": 5699,
        "model": "Outlander ",
        "status": "available",
        "id": "1f2ab3a7-c9c1-4bab-82a2-ba7c48a499a9",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9294,
        "license_plate_number": "8PLZ588",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 207,
        "model": "ECO Sport",
        "status": "on_rent",
        "id": "7bb6cfa5-a5fb-42d6-ae61-e04efcb565d2",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 24813,
        "license_plate_number": "660L91",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 4311,
        "model": "Compass",
        "status": "on_rent",
        "id": "c1316358-554c-4524-82de-738f5428912e",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 20276,
        "license_plate_number": "CPZ7134",
        "license_plate_state": "AZ",
        "make": "Toyota",
        "miles_until_service": 4905,
        "model": "Camry",
        "status": "available",
        "id": "7114f232-b651-492d-ae1c-6d8a39ed9461",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5494,
        "license_plate_number": "8PLP782",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 4006,
        "model": "Camry",
        "status": "on_rent",
        "id": "8d5aaa24-6d80-4fa5-9133-4651a8ce9071",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 13220,
        "license_plate_number": "CBW1013",
        "license_plate_state": "AZ",
        "make": "Toyota",
        "miles_until_service": 3780,
        "model": "Corolla",
        "status": "maintenance",
        "id": "c72dd720-6f3f-4689-91fd-163233b7edb9",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 11627,
        "license_plate_number": "2KZL54",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 5056,
        "model": "Optima LX",
        "status": "available",
        "id": "2173de32-e38a-4ce2-995e-dc2638e7dc31",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 10647,
        "license_plate_number": "2KZL44",
        "license_plate_state": "MA",
        "make": "Kia ",
        "miles_until_service": 5740,
        "model": "Optima LX",
        "status": "available",
        "id": "6ca4a923-9b59-4b0c-9466-8e9b6861eb47",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7701,
        "license_plate_number": "9GE562",
        "license_plate_state": "MA",
        "make": "Mitsubishi",
        "miles_until_service": 7988,
        "model": "Outlander",
        "status": "on_rent",
        "id": "43af6959-4b52-44a8-a982-3489a10d04f7",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 17037,
        "license_plate_number": "CTS7618",
        "license_plate_state": "AZ",
        "make": "Kia ",
        "miles_until_service": 5583,
        "model": "Optima",
        "status": "available",
        "id": "cd38a83f-b718-4847-b31e-b4dbea82d982",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 16579,
        "license_plate_number": "303LLV",
        "license_plate_state": "OR",
        "make": "Kia",
        "miles_until_service": 3236,
        "model": "Optima",
        "status": "on_rent",
        "id": "3f5632d5-cc5f-44de-a16a-97461ebcea49",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 13943,
        "license_plate_number": "9WE372",
        "license_plate_state": "MA",
        "make": "Chevy",
        "miles_until_service": 7963,
        "model": "Malibu",
        "status": "available",
        "id": "0bea4f2b-2879-4a62-9503-dce16da88bd3",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 15888,
        "license_plate_number": "8PKE116",
        "license_plate_state": "CA",
        "make": "Mitsubishi",
        "miles_until_service": 2112,
        "model": "Outlander",
        "status": "on_rent",
        "id": "fb600373-d038-4584-9952-8f5d97c928f1",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 22885,
        "license_plate_number": "280L51",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 1845,
        "model": "Compass",
        "status": "available",
        "id": "86375d9e-b058-4240-828e-b5dbd29ba25d",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9033,
        "license_plate_number": "8PWM200",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 467,
        "model": "Escape",
        "status": "available",
        "id": "2a68bbf7-f653-4298-9694-d13cf71be6e3",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 18360,
        "license_plate_number": "BVX2825",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 352,
        "model": "Rogue",
        "status": "on_rent",
        "id": "86824999-827d-4210-b387-6d676d0710e4",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 3930,
        "license_plate_number": "1DNN13",
        "license_plate_state": "MA",
        "make": "Mitsubishi",
        "miles_until_service": 3570,
        "model": "Outlander",
        "status": "on_rent",
        "id": "e5abf669-940c-44f8-9ccd-145c2086fb79",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 10921,
        "license_plate_number": "BSU2632",
        "license_plate_state": "WA",
        "make": "Ford",
        "miles_until_service": -1420,
        "model": "Eco Sport",
        "status": "on_rent",
        "id": "70243b93-7783-430e-bcbb-280274f03ae4",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6713,
        "license_plate_number": "1AZZ73",
        "license_plate_state": "MA",
        "make": "Nissan",
        "miles_until_service": 787,
        "model": "Altima",
        "status": "on_rent",
        "id": "2356aa3a-9721-435a-8560-4d47231eff29",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7038,
        "license_plate_number": "8PKF015",
        "license_plate_state": "CA",
        "make": "Mitsubishi ",
        "miles_until_service": -476,
        "model": "Outlander",
        "status": "maintenance",
        "id": "baf1da0d-8b36-402d-8eb2-7c0623de289c",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 6863,
        "license_plate_number": "G642CJ",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": 637,
        "model": "Versa",
        "status": "on_rent",
        "id": "b4bc68b6-7e16-47db-aea7-56b1bef401a4",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 13097,
        "license_plate_number": "BPM9128",
        "license_plate_state": "WA",
        "make": "Toyota",
        "miles_until_service": 3903,
        "model": "Corolla",
        "status": "on_rent",
        "id": "a0b554e4-aa7d-4936-8232-f736405fabf3",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 9807,
        "license_plate_number": "8LOZ477",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 6804,
        "model": "RAV-4",
        "status": "on_rent",
        "id": "6813e6ac-5d97-4b66-b836-82b12c9cfde8",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 3380,
        "license_plate_number": "8RBK517",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2120,
        "model": "Altima",
        "status": "on_rent",
        "id": "79307e09-0b5b-441a-9116-1eb49da76577",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 9568,
        "license_plate_number": "BTP1958",
        "license_plate_state": "WA",
        "make": "Nissan",
        "miles_until_service": 2470,
        "model": "Altima",
        "status": "available",
        "id": "3998be92-2a0e-4f05-8003-5a84a9daff19",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 13425,
        "license_plate_number": "8PJU275",
        "license_plate_state": "CA",
        "make": "Kia ",
        "miles_until_service": 2620,
        "model": "Optima",
        "status": "on_rent",
        "id": "f21e3886-17dd-4274-92ab-d05fd94e3612",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 47258,
        "license_plate_number": "8GYB880",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 6587,
        "model": "Versa",
        "status": "maintenance",
        "id": "29941842-14f6-4593-91a6-4020ec751e39",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 4993,
        "license_plate_number": "8RBJ760",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2507,
        "model": "Altima",
        "status": "available",
        "id": "99652889-954a-4599-92e9-a6967bc96b7d",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 2121,
        "license_plate_number": "8PKF446",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 7379,
        "model": "Corolla",
        "status": "available",
        "id": "a0550948-de71-4910-a10b-184f55bb26a9",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 22408,
        "license_plate_number": "EDA9221",
        "license_plate_state": "MI",
        "make": "Toyota",
        "miles_until_service": 3592,
        "model": "Corolla",
        "status": "on_rent",
        "id": "ccb786ab-d63c-4afb-8d90-92d8d22c9adf",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 4734,
        "license_plate_number": "8RAM452",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 7066,
        "model": "Elantra",
        "status": "maintenance",
        "id": "7687e53f-4ca5-45e0-8b3d-230763cf9948",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 3615,
        "license_plate_number": "8SAJ738",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 3885,
        "model": "Versa",
        "status": "on_rent",
        "id": "763171ea-1909-4471-8bd8-d2ed59f0822e",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 18667,
        "license_plate_number": "NDJ1892",
        "license_plate_state": "TX",
        "make": "Mitsubishi",
        "miles_until_service": 1836,
        "model": "Outlander",
        "status": "on_rent",
        "id": "06c3d8a2-a5ac-4175-a311-192f7a9c8d23",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 5109,
        "license_plate_number": "G958DL",
        "license_plate_state": "UT",
        "make": "Nissan ",
        "miles_until_service": 2391,
        "model": "Versa",
        "status": "on_rent",
        "id": "9fc94a0e-2e6d-4a22-b640-c20b49cce420",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6861,
        "license_plate_number": "8RBH708",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 2639,
        "model": "Fusion",
        "status": "on_rent",
        "id": "f2133032-6a91-4622-81e5-5e2052fcce05",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 36794,
        "license_plate_number": "8GXH339",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 6258,
        "model": "Versa",
        "status": "available",
        "id": "adcf3d8d-5ec6-4233-b2bf-c06d8553fce5",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 18106,
        "license_plate_number": "8NYK108",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 2929,
        "model": "Fusion",
        "status": "on_rent",
        "id": "c8e84a38-7882-4d37-8bab-fb521b2e4ad9",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 3585,
        "license_plate_number": "BTP1781",
        "license_plate_state": "WA",
        "make": "Ford",
        "miles_until_service": 17269,
        "model": "EcoSport",
        "status": "on_rent",
        "id": "54033ed0-7096-4d2a-ab6e-c142f76e5e79",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9381,
        "license_plate_number": "2KZL64",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 5222,
        "model": "Optima LX",
        "status": "available",
        "id": "37a0ff50-aef4-4c63-b54e-690d63d13a31",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5108,
        "license_plate_number": "JKJE67",
        "license_plate_state": "FL",
        "make": "Volvo",
        "miles_until_service": 4892,
        "model": "V60",
        "status": "available",
        "id": "cac93391-933b-41c7-8d9a-b482c8819545",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 18454,
        "license_plate_number": "CTL4477",
        "license_plate_state": "AZ",
        "make": "Toyota",
        "miles_until_service": 5523,
        "model": "Camry",
        "status": "available",
        "id": "008b5cb7-fed5-451c-a771-0e1a3be8f9c7",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 32613,
        "license_plate_number": "8KJC177",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 5884,
        "model": "Elantra",
        "status": "on_rent",
        "id": "b232d164-c12a-4ea1-b2d8-ff664101c02a",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 9200,
        "license_plate_number": "UJS8018",
        "license_plate_state": "VA",
        "make": "Honda",
        "miles_until_service": 4987,
        "model": "Accord",
        "status": "on_rent",
        "id": "bb717a02-7571-49f0-915e-b1ae92dfde8a",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 12139,
        "license_plate_number": "8PJU281",
        "license_plate_state": "CA",
        "make": "Kia ",
        "miles_until_service": 2833,
        "model": "Optima",
        "status": "on_rent",
        "id": "a5c629d9-71e7-4d78-8ce3-a6ec75bc1179",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7259,
        "license_plate_number": "8RBJ374",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 5991,
        "model": "Kona",
        "status": "on_rent",
        "id": "14e03ca8-2d91-422c-aeca-a01b1dd88115",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 3196,
        "license_plate_number": "G333CJ",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": 4304,
        "model": "Versa",
        "status": "maintenance",
        "id": "906a964c-aa1c-4fdb-bed3-04068acec4f6",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 37222,
        "license_plate_number": "8JUT131",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2506,
        "model": "Versa",
        "status": "on_rent",
        "id": "d65b0cd5-d5b1-4bcc-b6e5-e36ec3f65fa8",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6515,
        "license_plate_number": "G09OEC",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": 985,
        "model": "Versa",
        "status": "on_rent",
        "id": "abcf4c9f-7aa4-4bb2-ab93-e60f0a5831ca",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 11478,
        "license_plate_number": "832L80",
        "license_plate_state": "NV",
        "make": "Ford",
        "miles_until_service": 7584,
        "model": "Edge",
        "status": "available",
        "id": "c30346c9-ff89-45bb-b822-0652469ae597",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 22885,
        "license_plate_number": "8LXU951",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": -385,
        "model": "Elantra",
        "status": "available",
        "id": "54c562c6-a529-47ae-b287-c89b33b88953",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 2762,
        "license_plate_number": "G089EC",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": 4738,
        "model": "Versa",
        "status": "available",
        "id": "e214c9db-ee04-43cc-b988-600f9ecb3b7e",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 10564,
        "license_plate_number": "8PKE178",
        "license_plate_state": "CA",
        "make": "Mitsubishi ",
        "miles_until_service": 6936,
        "model": "Outlander",
        "status": "on_rent",
        "id": "08f219a5-48cb-4b19-a9cb-413fa48aef82",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 15462,
        "license_plate_number": "8PJU278",
        "license_plate_state": "CA",
        "make": "Kia ",
        "miles_until_service": -82,
        "model": "Optima",
        "status": "on_rent",
        "id": "5377748d-8e77-4868-8b8d-7aa8a8a3608f",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 6888,
        "license_plate_number": "8PTY805",
        "license_plate_state": "CA",
        "make": "VW",
        "miles_until_service": 2612,
        "model": "Passat",
        "status": "on_rent",
        "id": "3eebbb39-f2d2-428f-84b9-1440232e0394",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 10605,
        "license_plate_number": "CTS7622",
        "license_plate_state": "AZ",
        "make": "Kia ",
        "miles_until_service": 4167,
        "model": "Optima",
        "status": "on_rent",
        "id": "728ff7c7-c61c-4569-8351-4574db6a586c",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 45593,
        "license_plate_number": "8GYB724",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 1353,
        "model": "Versa",
        "status": "on_rent",
        "id": "ba6d8f18-5c95-485a-8f53-94684b0381db",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 40266,
        "license_plate_number": "884H71",
        "license_plate_state": "NV",
        "make": "Hyundai",
        "miles_until_service": 6193,
        "model": "Elantra",
        "status": "on_rent",
        "id": "1b273f71-baba-48b0-9fbf-5cc7c42881c1",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 29062,
        "license_plate_number": "BZM1514",
        "license_plate_state": "AZ",
        "make": "Kia",
        "miles_until_service": 6438,
        "model": "Forte",
        "status": "on_rent",
        "id": "46a42430-1bbd-4f5d-b833-7309266ae4d5",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 18074,
        "license_plate_number": "MMH4035",
        "license_plate_state": "TX",
        "make": "Mitsubishi",
        "miles_until_service": 4426,
        "model": "Outlander Sport",
        "status": "on_rent",
        "id": "186bd6a4-a2f9-484e-b269-878316c1c32d",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 4749,
        "license_plate_number": "8RBK629",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2751,
        "model": "Altima",
        "status": "maintenance",
        "id": "a268f6c2-8a1d-4527-b987-70055ddebebd",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 4002,
        "license_plate_number": "8SAN516",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 3498,
        "model": "Versa",
        "status": "on_rent",
        "id": "111f65a1-a2f3-4ffd-85c8-53748adec605",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 28699,
        "license_plate_number": "8KAM653",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 1301,
        "model": "Elantra",
        "status": "available",
        "id": "5d7e3517-7a9e-42b7-bee0-3f011f04ac3a",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 7127,
        "license_plate_number": "2KZL94",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 9320,
        "model": "Optima LX",
        "status": "on_rent",
        "id": "987e3476-71f9-4f8d-878f-a8fc5ca52005",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 15957,
        "license_plate_number": "9GN282",
        "license_plate_state": "MA",
        "make": "Chevy",
        "miles_until_service": 3043,
        "model": "Malibu",
        "status": "on_rent",
        "id": "e688b7ca-7fbb-48ac-9b8d-360009543cc4",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 21726,
        "license_plate_number": "960L89",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 5885,
        "model": "Compass",
        "status": "on_rent",
        "id": "b6bca519-3d6d-464c-96e5-7edd4217b504",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 7532,
        "license_plate_number": "8PKF419",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1969,
        "model": "Corolla",
        "status": "available",
        "id": "1aeeb52a-626f-400f-8b25-fc2d9d48f751",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 2179,
        "license_plate_number": "8PKD716",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 5322,
        "model": "Tucson",
        "status": "on_rent",
        "id": "8c0dfde6-95ae-44fb-ad50-7cbf153bec4d",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 21528,
        "license_plate_number": "8JQC593",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 6972,
        "model": "Sentra",
        "status": "available",
        "id": "2b6ee3dd-5bb1-4495-94e9-3e2734c0f0e4",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 4967,
        "license_plate_number": "8SAJ745",
        "license_plate_state": "CA",
        "make": "Niss",
        "miles_until_service": 2533,
        "model": "Versa",
        "status": "maintenance",
        "id": "1ca6f788-4eb2-4492-b824-f903a09d0cae",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 31966,
        "license_plate_number": "8LOH289",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 6469,
        "model": "Elantra",
        "status": "available",
        "id": "245c779b-0de0-4496-81a7-588ed04e7cbf",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 13635,
        "license_plate_number": "8PLY635",
        "license_plate_state": "CA",
        "make": "Mitsubishi",
        "miles_until_service": 1827,
        "model": "Outlander",
        "status": "on_rent",
        "id": "4b44f259-a322-476c-baae-096f315b039f",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 8564,
        "license_plate_number": "8RAL937",
        "license_plate_state": "CA",
        "make": "Honda ",
        "miles_until_service": 7155,
        "model": "Civic",
        "status": "on_rent",
        "id": "7ee3320d-58a9-4dcf-b496-2965917b0a94",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 15328,
        "license_plate_number": "8PTY059",
        "license_plate_state": "CA",
        "make": "Jeep",
        "miles_until_service": 3405,
        "model": "Compass Trailhawk",
        "status": "on_rent",
        "id": "3a26b3dd-864a-4982-af62-8d5f07fe1805",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 11620,
        "license_plate_number": "2KZK94",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 4886,
        "model": "Optima LX",
        "status": "available",
        "id": "ce0a5d27-f3b9-4aea-8994-3e97a2a1299d",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 14755,
        "license_plate_number": "8NYK575",
        "license_plate_state": "CA",
        "make": "Toyota ",
        "miles_until_service": 3147,
        "model": "Camry",
        "status": "available",
        "id": "9cef96f1-286b-4e7f-abdb-82a63aba7feb",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 6704,
        "license_plate_number": "8PWM617",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 5848,
        "model": "Altima",
        "status": "available",
        "id": "57291ac3-c130-4699-a7ab-c05bb12c5899",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 6605,
        "license_plate_number": "8RBK285",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 895,
        "model": "Altima",
        "status": "on_rent",
        "id": "79017535-39d4-464b-8486-5043a0dc90b6",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 5110,
        "license_plate_number": "G091EC",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": 2390,
        "model": "Versa",
        "status": "available",
        "id": "6610a957-5798-468d-a8f9-8d885edcda9d",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 25055,
        "license_plate_number": "8NFA037",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 5425,
        "model": "Versa",
        "status": "available",
        "id": "5677f1e9-43bc-4a9e-8647-fd7e9b5bf722",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 24230,
        "license_plate_number": "8LOY069",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": -143,
        "model": "Kona",
        "status": "maintenance",
        "id": "513cfdaa-b9d1-40ed-89cb-efd50875fe40",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 9501,
        "license_plate_number": "2KZL14",
        "license_plate_state": "MA",
        "make": "Kia",
        "miles_until_service": 6002,
        "model": "Optima LX",
        "status": "available",
        "id": "c2790f57-5c54-425a-8711-056395bc006e",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7764,
        "license_plate_number": "8PWK849",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1737,
        "model": "Corolla",
        "status": "available",
        "id": "66300db2-2bbb-4871-ab07-0e63b423222d",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7131,
        "license_plate_number": "G328CJ",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": 369,
        "model": "Versa",
        "status": "on_rent",
        "id": "54825637-a020-4d9c-9b4a-90bf40d132f6",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6950,
        "license_plate_number": "8RBK283",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 550,
        "model": "Altima",
        "status": "available",
        "id": "988c927b-9d02-41b0-9878-09548d45aa81",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5533,
        "license_plate_number": "V768YU",
        "license_plate_state": "UT",
        "make": "Ford",
        "miles_until_service": 3967,
        "model": "Escape",
        "status": "on_rent",
        "id": "3b5de401-f887-45a3-b26c-dad1a7376fd5",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 18903,
        "license_plate_number": "158L06",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 7499,
        "model": "Compass",
        "status": "on_rent",
        "id": "71bb27ea-7b06-4ec5-ad14-41cff97983d4",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 7934,
        "license_plate_number": "8PKD840",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": -2433,
        "model": "Kona",
        "status": "available",
        "id": "02d92dee-0450-43fe-9d0e-d5915f00fb6d",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 14132,
        "license_plate_number": "CTY1165",
        "license_plate_state": "AZ",
        "make": "Toyota",
        "miles_until_service": 3568,
        "model": "Camry",
        "status": "available",
        "id": "ebea715b-9d9a-4aec-9cb6-11f3855194e1",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 213,
        "license_plate_number": "DFWN97",
        "license_plate_state": "FL",
        "make": "Suburu",
        "miles_until_service": 6787,
        "model": "Outback",
        "status": "on_rent",
        "id": "14da91cd-f4ec-4345-97bf-707b68f8049f",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 9475,
        "license_plate_number": "8RBJ423",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 3525,
        "model": "Kona",
        "status": "available",
        "id": "16026e06-f959-45dd-880f-c8655c4963b4",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 9661,
        "license_plate_number": "8PWK571",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": -161,
        "model": "Camry",
        "status": "available",
        "id": "c245cb9f-4cb8-4899-ab9b-572ad5fa9a1e",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 2123,
        "license_plate_number": "8RBH290",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 7377,
        "model": "EcoSport",
        "status": "on_rent",
        "id": "69c08d5a-0021-44a9-a6a1-2cbaceaec93b",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 8616,
        "license_plate_number": "8RBJ577",
        "license_plate_state": "CA",
        "make": "Honda",
        "miles_until_service": -1116,
        "model": "Civic",
        "status": "maintenance",
        "id": "a736fc00-f6dd-4dd5-9665-9c2c4e70a8ec",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 13566,
        "license_plate_number": "8PLZ888",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 5834,
        "model": "Camry",
        "status": "on_rent",
        "id": "1dbc9490-4070-4d50-992f-29255620db82",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 5723,
        "license_plate_number": "8PTZ565",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1777,
        "model": "Camry",
        "status": "on_rent",
        "id": "a5f0807c-8a60-4383-8d4e-a7b8fcb86eca",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 319,
        "license_plate_number": "JKBA78",
        "license_plate_state": "FL",
        "make": "Suburu",
        "miles_until_service": 6681,
        "model": "Outback",
        "status": "on_rent",
        "id": "2ab6b9de-ef2c-42f6-b465-aba163fa918b",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 40297,
        "license_plate_number": "8JUT119",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 3592,
        "model": "Versa",
        "status": "on_rent",
        "id": "dec72920-63a6-467c-97a6-e2720b5a3b56",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 47783,
        "license_plate_number": "8GWU379",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 6046,
        "model": "Versa",
        "status": "available",
        "id": "1b3805d0-180c-4a80-9e00-64a201438b1e",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 20005,
        "license_plate_number": "BD3L1L",
        "license_plate_state": "WA",
        "make": "Mitsubishi",
        "miles_until_service": 7489,
        "model": "Eclipse Cross",
        "status": "on_rent",
        "id": "109e43dd-5b64-48eb-b42a-f8fa0ebf6e68",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 7706,
        "license_plate_number": "8PKD670",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1794,
        "model": "Camry",
        "status": "on_rent",
        "id": "f0e02875-842d-43a7-bde7-4dc3529ccc92",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 29852,
        "license_plate_number": "151L06",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 1321,
        "model": "Compass",
        "status": "on_rent",
        "id": "58e7800e-d375-4b0c-b6f0-568c808c53e6",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 6976,
        "license_plate_number": "8RAM450",
        "license_plate_state": "CA",
        "make": "Nissan ",
        "miles_until_service": -1475,
        "model": "Versa",
        "status": "maintenance",
        "id": "977c75c4-a288-4e6c-a310-56750ba5e0c1",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 1759,
        "license_plate_number": "8PKD786",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 3742,
        "model": "Kona",
        "status": "on_rent",
        "id": "709f121a-c81f-4fd9-abcb-a91a725e6477",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 4400,
        "license_plate_number": "8PKD657",
        "license_plate_state": "CA",
        "make": "Hyundai",
        "miles_until_service": 1101,
        "model": "Kona",
        "status": "on_rent",
        "id": "c6bea244-13d7-4ecf-bba1-60e572f2149a",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 19514,
        "license_plate_number": "618038C",
        "license_plate_state": "MT",
        "make": "Toyota",
        "miles_until_service": 7492,
        "model": "Corolla",
        "status": "available",
        "id": "41e77d7f-ae82-4e1a-9f5b-b20db2e36572",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 23753,
        "license_plate_number": "446L91",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 1447,
        "model": "Compass",
        "status": "available",
        "id": "eb75058a-e4f4-4005-9865-d7a04f03629d",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 36117,
        "license_plate_number": "8GYS513",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 6948,
        "model": "Versa",
        "status": "available",
        "id": "8b85eeb1-b1d7-47c2-9adc-aa1604e11977",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 6918,
        "license_plate_number": "8LOZ346",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 6922,
        "model": "Camry",
        "status": "available",
        "id": "691e3a2f-e490-49ba-ac7e-5e0f7631b086",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 7899,
        "license_plate_number": "8NYK753",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 1602,
        "model": "Rav 4",
        "status": "on_rent",
        "id": "464502b7-80d2-4d2d-8c17-b4326eb222aa",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 7459,
        "license_plate_number": "8PLP734",
        "license_plate_state": "CA",
        "make": "Mitsubishi ",
        "miles_until_service": 7077,
        "model": "Outlander Sport",
        "status": "on_rent",
        "id": "5e69b857-421f-4f9e-ae07-1010a906d4be",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 20749,
        "license_plate_number": "CFE5296",
        "license_plate_state": "AZ",
        "make": "Hyundai",
        "miles_until_service": 1751,
        "model": "Kona",
        "status": "available",
        "id": "c18e801a-529b-4941-9de2-df53c7182528",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 27061,
        "license_plate_number": "8GXG792",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 20087,
        "model": "Versa",
        "status": "maintenance",
        "id": "fc02d8e7-f5d9-488d-a9c1-72f2884f0258",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 21257,
        "license_plate_number": "8LOY071",
        "license_plate_state": "CA",
        "make": "Mitsubishi ",
        "miles_until_service": 1892,
        "model": "Outlander",
        "status": "maintenance",
        "id": "db13eb15-e823-451f-90ac-76395b9b1fc8",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 46465,
        "license_plate_number": "8GWU131",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2155,
        "model": "Versa",
        "status": "on_rent",
        "id": "82adbbfc-4d94-431a-90f9-cd67e891c0aa",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 16461,
        "license_plate_number": "8PJU274",
        "license_plate_state": "CA",
        "make": "Kia ",
        "miles_until_service": 6785,
        "model": "Optima",
        "status": "available",
        "id": "81dc8ed9-cf41-4475-b615-eec798b5c3fa",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 16946,
        "license_plate_number": "8PTY266",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 3854,
        "model": "Camry",
        "status": "on_rent",
        "id": "d6cf85e0-1fc3-47c7-93e6-ed4bd213ba0f",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 42019,
        "license_plate_number": "796K26",
        "license_plate_state": "NV",
        "make": "Jeep",
        "miles_until_service": 5626,
        "model": "Compass",
        "status": "available",
        "id": "71ea9b03-04dd-4149-8b28-b344206dfea9",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 6513,
        "license_plate_number": "BTP0400",
        "license_plate_state": "WA",
        "make": "Nissan",
        "miles_until_service": -1012,
        "model": "Altima",
        "status": "on_rent",
        "id": "518ed3b9-22f2-4df6-b683-62435b894a9a",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 17407,
        "license_plate_number": "CTL4117",
        "license_plate_state": "AZ",
        "make": "Mitsubishi",
        "miles_until_service": 1172,
        "model": "Outlander",
        "status": "on_rent",
        "id": "43855627-9c47-4177-a255-44728c45ba33",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 21064,
        "license_plate_number": "8NSE666",
        "license_plate_state": "CA",
        "make": "Chevy",
        "miles_until_service": 4407,
        "model": "Equinox",
        "status": "on_rent",
        "id": "753aad34-94c7-49e1-a443-df8012ba0b4f",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 2456,
        "license_plate_number": "8PWM149",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 9476,
        "model": "Fusion",
        "status": "on_rent",
        "id": "934a3f11-7ff9-46af-8fcd-a8bbbfd510f9",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 8660,
        "license_plate_number": "8RBH354",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 840,
        "model": "EcoSport",
        "status": "available",
        "id": "5042c417-b2b4-42be-afff-2a0d9d0efb4d",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 7273,
        "license_plate_number": "8LOZ676",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 2227,
        "model": "Camry",
        "status": "on_rent",
        "id": "f2de4a09-18a1-4552-af40-0aafa98912b2",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 12151,
        "license_plate_number": "8BMG236",
        "license_plate_state": "ID",
        "make": "Ford",
        "miles_until_service": 7468,
        "model": "Escape",
        "status": "on_rent",
        "id": "68a7f449-d410-4fda-ac0a-39079fe5f05d",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 19455,
        "license_plate_number": "8LOZ642",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": -25,
        "model": "Camry",
        "status": "on_rent",
        "id": "1cfb7ac2-8843-4b15-80fe-b105baf3667c",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 7851,
        "license_plate_number": "G325CJ",
        "license_plate_state": "UT",
        "make": "Nissan",
        "miles_until_service": -351,
        "model": "Versa",
        "status": "on_rent",
        "id": "0b377465-0ed0-45e5-9dc5-2091d0e149de",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 5414,
        "license_plate_number": "8PWM034",
        "license_plate_state": "CA",
        "make": "Ford",
        "miles_until_service": 4086,
        "model": "Fusion",
        "status": "maintenance",
        "id": "d836fbe7-c03e-49e1-bbfb-edc4fbc09974",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 13519,
        "license_plate_number": "8LOZ534",
        "license_plate_state": "CA",
        "make": "Toyota",
        "miles_until_service": 7122,
        "model": "Camry",
        "status": "available",
        "id": "f1020474-3e5c-41d9-b4d6-8ac4a5eff628",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 11778,
        "license_plate_number": "8PWL764",
        "license_plate_state": "CA",
        "make": "Nissan",
        "miles_until_service": 2107,
        "model": "Altima",
        "status": "on_rent",
        "id": "270fe7bf-fec5-46f6-a8b0-397da3fc2f3b",
        "vehicle_class": "Sedan"
    },
    {
        "last_mileage_reported": 7331,
        "license_plate_number": "8RAL425",
        "license_plate_state": "CA",
        "make": "Honda",
        "miles_until_service": 2169,
        "model": "Accord",
        "status": "on_rent",
        "id": "23b18455-fd7e-41b2-958f-0c4fa2286534",
        "vehicle_class": "Economy"
    },
    {
        "last_mileage_reported": 9826,
        "license_plate_number": "BSU1487",
        "license_plate_state": "WA",
        "make": "Mitsubishi",
        "miles_until_service": 6674,
        "model": "Outlander",
        "status": "on_rent",
        "id": "12bf5134-cad2-4a4d-9dad-6fc465b6904e",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 17931,
        "license_plate_number": "8LOY400",
        "license_plate_state": "CA",
        "make": "Mitsubishi ",
        "miles_until_service": 5569,
        "model": "Outlander",
        "status": "on_rent",
        "id": "5336e0f7-80e5-4ff0-8d4c-d36b13ae8cce",
        "vehicle_class": "SUV"
    },
    {
        "last_mileage_reported": 7946,
        "license_plate_number": "BSU1154",
        "license_plate_state": "WA",
        "make": "Mitsubishi",
        "miles_until_service": 4873,
        "model": "Outlander",
        "status": "on_rent",
        "id": "94f7dd21-ae6a-4b0b-8ae7-cc81b33d316b",
        "vehicle_class": "SUV"
    }
]
}

def update_vehicles(data):
    vehicles_entries = []
    for vehicles in data["all_vehicles"]:
        new_entry = Vehicle(last_mileage_reported=vehicles['last_mileage_reported'],
        license_plate_state=vehicles['license_plate_state'],
        make=vehicles['make'],
        miles_until_service=vehicles['miles_until_service'],
        model=vehicles['model'],
        status=vehicles['status'],
        vehicle_class=vehicles['vehicle_class'],
                            license_plate_number=vehicles['license_plate_number'])
        vehicles_entries.append(new_entry)
    db.session.add_all(vehicles_entries)
    db.session.commit()
